export const NAMES_OF_MUHAMMAD = [
  { name: 'مُحَمَّد', transliteration: 'Muhammad', en: { meaning: 'The Praised One' }, ur: { meaning: 'جس کی بہت تعریف کی گئی ہو' } },
  { name: 'أَحْمَد', transliteration: 'Ahmad', en: { meaning: 'Most Commendable' }, ur: { meaning: 'بہت تعریف کرنے والا' } },
  { name: 'حَامِد', transliteration: 'Hamid', en: { meaning: 'Praising' }, ur: { meaning: 'تعریف کرنے والا' } },
  { name: 'مَحْمُود', transliteration: 'Mahmud', en: { meaning: 'The Praised' }, ur: { meaning: 'قابل تعریف' } },
  { name: 'قَاسِم', transliteration: 'Qasim', en: { meaning: 'The Distributor' }, ur: { meaning: 'تقسیم کرنے والا' } },
  { name: 'عَاقِب', transliteration: 'Aqib', en: { meaning: 'The Successor' }, ur: { meaning: 'پیچھے آنے والا' } },
  { name: 'فَاتِح', transliteration: 'Fatih', en: { meaning: 'The Opener' }, ur: { meaning: 'فتح کرنے والا' } },
  { name: 'خَاتَم', transliteration: 'Khatam', en: { meaning: 'The Seal' }, ur: { meaning: 'مہر / آخری' } },
  { name: 'حَاشِر', transliteration: 'Hashir', en: { meaning: 'The Gatherer' }, ur: { meaning: 'جمع کرنے والا' } },
  { name: 'مَاحِی', transliteration: 'Mahi', en: { meaning: 'The Eraser' }, ur: { meaning: 'مٹانے والا' } },
  { name: 'طٰهٰ', transliteration: 'Taha', en: { meaning: 'Taha (Mystic Title)' }, ur: { meaning: 'طہٰ' } },
  { name: 'يٰسٓ', transliteration: 'Yasin', en: { meaning: 'Yasin (Mystic Title)' }, ur: { meaning: 'یسین' } },
  { name: 'مُزَّمِّل', transliteration: 'Muzzammil', en: { meaning: 'The Enwrapped One' }, ur: { meaning: 'کمبل لپیٹنے والا' } },
  { name: 'مُدَّثِّر', transliteration: 'Muddathir', en: { meaning: 'The Shrouded One' }, ur: { meaning: 'چادر اوڑھنے والا' } },
  { name: 'شَاهِد', transliteration: 'Shahid', en: { meaning: 'The Witness' }, ur: { meaning: 'گواہی دینے والا' } },
  { name: 'مُبَشِّر', transliteration: 'Mubashir', en: { meaning: 'The Giver of Glad Tidings' }, ur: { meaning: 'خوشخبری دینے والا' } },
  { name: 'نَذِير', transliteration: 'Nadhir', en: { meaning: 'The Warner' }, ur: { meaning: 'ڈر سنانے والا' } },
  { name: 'دَاعِی', transliteration: 'Da\'i', en: { meaning: 'The Caller' }, ur: { meaning: 'بلانے والا' } },
  { name: 'سِرَاج', transliteration: 'Siraj', en: { meaning: 'The Lamp' }, ur: { meaning: 'روشن چراغ' } },
  { name: 'مُنِير', transliteration: 'Munir', en: { meaning: 'The Radiant' }, ur: { meaning: 'روشن کرنے والا' } },
  { name: 'رؤُوف', transliteration: 'Ra\'uf', en: { meaning: 'The Kind' }, ur: { meaning: 'بہت مہربان' } },
  { name: 'رَحِيم', transliteration: 'Rahim', en: { meaning: 'The Merciful' }, ur: { meaning: 'رحم کرنے والا' } },
  { name: 'مُصْطَفٰی', transliteration: 'Mustafa', en: { meaning: 'The Chosen One' }, ur: { meaning: 'چنیدہ' } },
  { name: 'مُجْتَبٰی', transliteration: 'Mujtaba', en: { meaning: 'The Selected' }, ur: { meaning: 'منتخب کیا گیا' } },
  { name: 'مُرتَضٰی', transliteration: 'Murtada', en: { meaning: 'The Pleased' }, ur: { meaning: 'جس سے اللہ راضی ہو' } },
  { name: 'أَمِين', transliteration: 'Amin', en: { meaning: 'The Trustworthy' }, ur: { meaning: 'امانت دار' } },
  { name: 'صَادِق', transliteration: 'Sadiq', en: { meaning: 'The Truthful' }, ur: { meaning: 'سچا' } },
  { name: 'سَيِّد', transliteration: 'Sayyid', en: { meaning: 'The Master' }, ur: { meaning: 'سردار' } },
  { name: 'حَبِيب', transliteration: 'Habib', en: { meaning: 'The Beloved' }, ur: { meaning: 'محبوب' } },
  { name: 'كَرِيم', transliteration: 'Karim', en: { meaning: 'The Generous' }, ur: { meaning: 'کرم کرنے والا' } },
  { name: 'شَفِيع', transliteration: 'Shafi\'', en: { meaning: 'The Intercessor' }, ur: { meaning: 'شفاعت کرنے والا' } },
  { name: 'نَبِيّ', transliteration: 'Nabi', en: { meaning: 'The Prophet' }, ur: { meaning: 'نبی' } },
  { name: 'رَسُول', transliteration: 'Rasul', en: { meaning: 'The Messenger' }, ur: { meaning: 'رسول' } },
  { name: 'طَاهِر', transliteration: 'Tahir', en: { meaning: 'The Pure' }, ur: { meaning: 'پاک' } },
  { name: 'طَيِّب', transliteration: 'Tayyib', en: { meaning: 'The Good' }, ur: { meaning: 'پاکیزہ' } },
  { name: 'مَنْصُور', transliteration: 'Mansur', en: { meaning: 'The Victorious' }, ur: { meaning: 'مدد دیا ہوا' } },
  { name: 'مُقْتَدِر', transliteration: 'Muqtadir', en: { meaning: 'The Powerful' }, ur: { meaning: 'قدرت والا' } },
  { name: 'بَشِير', transliteration: 'Bashir', en: { meaning: 'The Bringer of Good News' }, ur: { meaning: 'بشارت دینے والا' } },
  { name: 'نَصِير', transliteration: 'Nasir', en: { meaning: 'The Helper' }, ur: { meaning: 'مددگار' } },
  { name: 'مُتَوَكِّل', transliteration: 'Mutawakkil', en: { meaning: 'The Trusting in Allah' }, ur: { meaning: 'توکل کرنے والا' } },
  { name: 'شَكُور', transliteration: 'Shakur', en: { meaning: 'The Most Grateful' }, ur: { meaning: 'قدر دان' } },
  { name: 'مُنِيب', transliteration: 'Munib', en: { meaning: 'The Penitent' }, ur: { meaning: 'رجوع کرنے والا' } },
  { name: 'عَدْل', transliteration: 'Adl', en: { meaning: 'The Just' }, ur: { meaning: 'انصاف کرنے والا' } },
  { name: 'جَوَّاد', transliteration: 'Jawwad', en: { meaning: 'The Bountiful' }, ur: { meaning: 'سخی' } },
  { name: 'عَزِيز', transliteration: 'Aziz', en: { meaning: 'The Mighty' }, ur: { meaning: 'عزت والا' } },
  { name: 'مُقَدَّس', transliteration: 'Muqaddas', en: { meaning: 'The Holy' }, ur: { meaning: 'مقدس' } },
  { name: 'عَالِم', transliteration: 'Alim', en: { meaning: 'The Knowing' }, ur: { meaning: 'جاننے والا' } },
  { name: 'أَبْطَحِی', transliteration: 'Abtahi', en: { meaning: 'Belonging to Batha' }, ur: { meaning: 'ابطحی' } },
  { name: 'هَادِی', transliteration: 'Hadi', en: { meaning: 'The Guide' }, ur: { meaning: 'ہدایت دینے والا' } },
  { name: 'مَهْدِی', transliteration: 'Mahdi', en: { meaning: 'The Rightly Guided' }, ur: { meaning: 'ہدایت یافتہ' } },
  { name: 'مَحِيّ', transliteration: 'Muhi', en: { meaning: 'The Reviver' }, ur: { meaning: 'زندہ کرنے والا' } },
  { name: 'مَكِّی', transliteration: 'Makki', en: { meaning: 'The Meccan' }, ur: { meaning: 'مکی' } },
  { name: 'مَدَنِی', transliteration: 'Madani', en: { meaning: 'The Medinan' }, ur: { meaning: 'مدنی' } },
  { name: 'عَرَبِی', transliteration: 'Arabi', en: { meaning: 'The Arab' }, ur: { meaning: 'عربی' } },
  { name: 'هَاشِمِی', transliteration: 'Hashimi', en: { meaning: 'The Hashimite' }, ur: { meaning: 'ہاشمی' } },
  { name: 'قُرَشِی', transliteration: 'Qurayshi', en: { meaning: 'The Qurayshite' }, ur: { meaning: 'قریشی' } },
  { name: 'تِهَامِی', transliteration: 'Tihami', en: { meaning: 'The Tihaman' }, ur: { meaning: 'تہامی' } },
  { name: 'حِجَازِی', transliteration: 'Hijazi', en: { meaning: 'The Hijazite' }, ur: { meaning: 'حجازی' } },
  { name: 'نَذِير', transliteration: 'Nadhir', en: { meaning: 'The Warner' }, ur: { meaning: 'ڈرانے والا' } },
  { name: 'مُقْتَصِد', transliteration: 'Muqtasid', en: { meaning: 'The Frugal' }, ur: { meaning: 'اعتدال پسند' } },
  { name: 'مُبَلِّغ', transliteration: 'Muballigh', en: { meaning: 'The Conveyer' }, ur: { meaning: 'پہنچانے والا' } },
  { name: 'مُتَمِّم', transliteration: 'Mutammim', en: { meaning: 'The Perfector' }, ur: { meaning: 'مکمل کرنے والا' } },
  { name: 'عَفُوّ', transliteration: 'Afuww', en: { meaning: 'The Forgiver' }, ur: { meaning: 'معاف کرنے والا' } },
  { name: 'مُكَفَّى', transliteration: 'Mukaffa', en: { meaning: 'The Sufficient' }, ur: { meaning: 'کفایت کرنے والا' } },
  { name: 'مُقَفِّي', transliteration: 'Muqaffi', en: { meaning: 'The Last in line' }, ur: { meaning: 'آخر میں آنے والا' } },
  { name: 'نَاقِم', transliteration: 'Naqim', en: { meaning: 'The Avenger' }, ur: { meaning: 'انتقام لینے والا' } },
  { name: 'جَامِع', transliteration: 'Jami', en: { meaning: 'The Comprehensive' }, ur: { meaning: 'جامع' } },
  { name: 'مُقْتَفِی', transliteration: 'Muqtafi', en: { meaning: 'The Follower' }, ur: { meaning: 'پیروی کرنے والا' } },
  { name: 'مُصْلِح', transliteration: 'Muslih', en: { meaning: 'The Reformer' }, ur: { meaning: 'اصلاح کرنے والا' } },
  { name: 'كَرِيم', transliteration: 'Karim', en: { meaning: 'The Noble' }, ur: { meaning: 'شریف / کریم' } },
  { name: 'عَظِيم', transliteration: 'Azim', en: { meaning: 'The Great' }, ur: { meaning: 'عظیم' } },
  { name: 'حَكِيم', transliteration: 'Hakim', en: { meaning: 'The Wise' }, ur: { meaning: 'حکیم' } },
  { name: 'مُجِيب', transliteration: 'Mujib', en: { meaning: 'The Answerer' }, ur: { meaning: 'جواب دینے والا' } },
  { name: 'صَبُور', transliteration: 'Sabur', en: { meaning: 'The Patient' }, ur: { meaning: 'صابر' } },
  { name: 'حَلِيم', transliteration: 'Halim', en: { meaning: 'The Forbearing' }, ur: { meaning: 'بردبار' } },
  { name: 'مُعَلِّم', transliteration: 'Mu\'allim', en: { meaning: 'The Teacher' }, ur: { meaning: 'استاد' } },
  { name: 'بُرْهَان', transliteration: 'Burhan', en: { meaning: 'The Proof' }, ur: { meaning: 'دلیل' } },
  { name: 'حُجَّة', transliteration: 'Hujjah', en: { meaning: 'The Argument' }, ur: { meaning: 'حجت' } },
  { name: 'نُور', transliteration: 'Nur', en: { meaning: 'The Light' }, ur: { meaning: 'نور' } },
  { name: 'سِرَاج', transliteration: 'Siraj', en: { meaning: 'The Lamp' }, ur: { meaning: 'چراغ' } },
  { name: 'شَمْس', transliteration: 'Shams', en: { meaning: 'The Sun' }, ur: { meaning: 'سورج' } },
  { name: 'قَمَر', transliteration: 'Qamar', en: { meaning: 'The Moon' }, ur: { meaning: 'چاند' } },
  { name: 'رَحْمَة', transliteration: 'Rahmah', en: { meaning: 'The Mercy' }, ur: { meaning: 'رحمت' } },
  { name: 'غَوْث', transliteration: 'Ghawth', en: { meaning: 'The Helper' }, ur: { meaning: 'فریاد رس' } },
  { name: 'غَيَاث', transliteration: 'Ghiyath', en: { meaning: 'The Succourer' }, ur: { meaning: 'مددگار' } },
  { name: 'مَلَاذ', transliteration: 'Maladh', en: { meaning: 'The Refuge' }, ur: { meaning: 'پناہ گاہ' } },
  { name: 'عِيَاذ', transliteration: 'Iyadh', en: { meaning: 'The Protection' }, ur: { meaning: 'پناہ' } },
  { name: 'أَمَان', transliteration: 'Aman', en: { meaning: 'The Security' }, ur: { meaning: 'امن' } },
  { name: 'عِصْمَة', transliteration: 'Ismah', en: { meaning: 'The Innocence' }, ur: { meaning: 'عصمت' } },
  { name: 'مُحَرَّم', transliteration: 'Muharram', en: { meaning: 'The Forbidden' }, ur: { meaning: 'محترم' } },
  { name: 'مُقَدَّس', transliteration: 'Muqaddas', en: { meaning: 'The Sanctified' }, ur: { meaning: 'پاک' } },
  { name: 'مُبَارَك', transliteration: 'Mubarak', en: { meaning: 'The Blessed' }, ur: { meaning: 'مبارک' } },
  { name: 'مُطَهَّر', transliteration: 'Mutahhar', en: { meaning: 'The Purified' }, ur: { meaning: 'پاک کیا ہوا' } },
  { name: 'مُجْتَبٰی', transliteration: 'Mujtaba', en: { meaning: 'The Chosen' }, ur: { meaning: 'منتخب' } },
  { name: 'مُصْطَفٰی', transliteration: 'Mustafa', en: { meaning: 'The Selected' }, ur: { meaning: 'مصطفیٰ' } },
  { name: 'مُكَرَّم', transliteration: 'Mukarram', en: { meaning: 'The Honored' }, ur: { meaning: 'معزز' } },
  { name: 'مُجَلِّی', transliteration: 'Mujalli', en: { meaning: 'The Illuminator' }, ur: { meaning: 'روشن کرنے والا' } },
  { name: 'مُتَهَجِّد', transliteration: 'Mutahajjid', en: { meaning: 'The Night Worshipper' }, ur: { meaning: 'تہجد گزار' } },
  { name: 'فَارُوق', transliteration: 'Faruq', en: { meaning: 'The Distinguisher' }, ur: { meaning: 'فرق کرنے والا' } },
  { name: 'مُصَدِّق', transliteration: 'Musaddiq', en: { meaning: 'The Confirmer' }, ur: { meaning: 'تصدیق کرنے والا' } },
  { name: 'مُبِين', transliteration: 'Mubin', en: { meaning: 'The Manifest' }, ur: { meaning: 'واضح' } },
  { name: 'قَوِی', transliteration: 'Qawi', en: { meaning: 'The Powerful' }, ur: { meaning: 'قوی' } },
  { name: 'مُقْتَدِر', transliteration: 'Muqtadir', en: { meaning: 'The Dominant' }, ur: { meaning: 'قدرت والا' } },
  { name: 'مَكِين', transliteration: 'Makin', en: { meaning: 'The Firmly Established' }, ur: { meaning: 'مضبوط' } },
  { name: 'عَفُوّ', transliteration: 'Afuww', en: { meaning: 'The Pardoner' }, ur: { meaning: 'معاف کرنے والا' } },
  { name: 'مُطِيع', transliteration: 'Muti', en: { meaning: 'The Obedient' }, ur: { meaning: 'فرمانبردار' } },
  { name: 'مُقْتَصِد', transliteration: 'Muqtasid', en: { meaning: 'The Moderate' }, ur: { meaning: 'میانہ روی والا' } },
  { name: 'صَفِی', transliteration: 'Safi', en: { meaning: 'The Pure Friend' }, ur: { meaning: 'برگزیدہ' } },
  { name: 'مُجِير', transliteration: 'Mujir', en: { meaning: 'The Protector' }, ur: { meaning: 'پناہ دینے والا' } },
  { name: 'وَلِی', transliteration: 'Wali', en: { meaning: 'The Patron' }, ur: { meaning: 'سرپرست' } },
  { name: 'نَاصِر', transliteration: 'Nasir', en: { meaning: 'The Helper' }, ur: { meaning: 'مددگار' } },
  { name: 'مَنْصُور', transliteration: 'Mansur', en: { meaning: 'The Aided' }, ur: { meaning: 'منصور' } },
  { name: 'شَفِی', transliteration: 'Shafi', en: { meaning: 'The Healer' }, ur: { meaning: 'شفا دینے والا' } },
  { name: 'مُطَهَّر', transliteration: 'Mutahhar', en: { meaning: 'The Purified' }, ur: { meaning: 'پاک کیا گیا' } },
  { name: 'طَاهِر', transliteration: 'Tahir', en: { meaning: 'The Pure' }, ur: { meaning: 'طاہر' } },
  { name: 'قَرِيب', transliteration: 'Qarib', en: { meaning: 'The Near' }, ur: { meaning: 'قریب' } },
  { name: 'مَاء', transliteration: 'Ma\'', en: { meaning: 'The Water' }, ur: { meaning: 'پانی' } },
  { name: 'خَلِيل', transliteration: 'Khalil', en: { meaning: 'The Intimate Friend' }, ur: { meaning: 'خلیل' } },
  { name: 'صَاحِب', transliteration: 'Sahib', en: { meaning: 'The Companion' }, ur: { meaning: 'ساتھی' } },
  { name: 'مُصَفَّى', transliteration: 'Musaffa', en: { meaning: 'The One Sifted' }, ur: { meaning: 'منتخب' } },
  { name: 'مُرْتَضِی', transliteration: 'Murtada', en: { meaning: 'The Pleased' }, ur: { meaning: 'پسندیدہ' } },
  { name: 'مُعْطِی', transliteration: 'Mu\'ti', en: { meaning: 'The Giver' }, ur: { meaning: 'عطا کرنے والا' } },
  { name: 'نُور', transliteration: 'Nur', en: { meaning: 'The Light' }, ur: { meaning: 'نور' } },
  { name: 'رَسُولُ الرَّحْمَة', transliteration: 'Rasul al-Rahmah', en: { meaning: 'The Messenger of Mercy' }, ur: { meaning: 'رحمت کا رسول' } },
  { name: 'قَيِّم', transliteration: 'Qayyim', en: { meaning: 'The Upright' }, ur: { meaning: 'قیّم' } },
  { name: 'مُقِيم', transliteration: 'Muqim', en: { meaning: 'The Establisher' }, ur: { meaning: 'قائم کرنے والا' } },
  { name: 'جَامِع', transliteration: 'Jami', en: { meaning: 'The Assembler' }, ur: { meaning: 'جامع' } },
  { name: 'مُصْلِح', transliteration: 'Muslih', en: { meaning: 'The Conciliator' }, ur: { meaning: 'اصلاح کرنے والا' } },
  { name: 'عَدْل', transliteration: 'Adl', en: { meaning: 'The Just' }, ur: { meaning: 'انصاف پسند' } },
  { name: 'حَكِيم', transliteration: 'Hakim', en: { meaning: 'The Wise' }, ur: { meaning: 'حکیم' } },
  { name: 'فَصِيح', transliteration: 'Fasih', en: { meaning: 'The Eloquent' }, ur: { meaning: 'فصیح' } },
  { name: 'حَمِيد', transliteration: 'Hamid', en: { meaning: 'The Praiseworthy' }, ur: { meaning: 'حمید' } },
  { name: 'بَرّ', transliteration: 'Barr', en: { meaning: 'The Pious' }, ur: { meaning: 'نیک' } },
  { name: 'مُسْتَقِيم', transliteration: 'Mustaqim', en: { meaning: 'The Steadfast' }, ur: { meaning: 'سیدھا' } },
  { name: 'أُمِّی', transliteration: 'Ummi', en: { meaning: 'The Unlettered' }, ur: { meaning: 'امی' } },
  { name: 'عَزِيز', transliteration: 'Aziz', en: { meaning: 'The Honorable' }, ur: { meaning: 'عزیز' } },
  { name: 'حَرِيص', transliteration: 'Haris', en: { meaning: 'The Solicitious' }, ur: { meaning: 'خواہشمند' } },
  { name: 'رؤُوف', transliteration: 'Ra\'uf', en: { meaning: 'The Kind' }, ur: { meaning: 'مہربان' } },
  { name: 'رَحِيم', transliteration: 'Rahim', en: { meaning: 'The Merciful' }, ur: { meaning: 'رحیم' } },
  { name: 'كَرِيم', transliteration: 'Karim', en: { meaning: 'The Generous' }, ur: { meaning: 'سخی' } },
  { name: 'صَبُور', transliteration: 'Sabur', en: { meaning: 'The Patient' }, ur: { meaning: 'صابر' } },
  { name: 'ذِكْر', transliteration: 'Dhikr', en: { meaning: 'The Remembrance' }, ur: { meaning: 'ذکر' } },
  { name: 'أَبْطَحِی', transliteration: 'Abtahi', en: { meaning: 'Of the Batha' }, ur: { meaning: 'ابطحی' } },
  { name: 'مَكِّی', transliteration: 'Makki', en: { meaning: 'The Meccan' }, ur: { meaning: 'مکی' } },
  { name: 'مَدَنِی', transliteration: 'Madani', en: { meaning: 'The Medinan' }, ur: { meaning: 'مدنی' } },
  { name: 'تِهَامِی', transliteration: 'Tihami', en: { meaning: 'The Tihaman' }, ur: { meaning: 'تہامی' } },
  { name: 'عَرَبِی', transliteration: 'Arabi', en: { meaning: 'The Arab' }, ur: { meaning: 'عربی' } },
  { name: 'حِجَازِی', transliteration: 'Hijazi', en: { meaning: 'The Hijazi' }, ur: { meaning: 'حجازی' } },
  { name: 'قُرَشِی', transliteration: 'Qurashi', en: { meaning: 'The Qurayshi' }, ur: { meaning: 'قریشی' } },
  { name: 'هَاشِمِی', transliteration: 'Hashimi', en: { meaning: 'The Hashemite' }, ur: { meaning: 'ہاشمی' } },
  { name: 'أَوْطَحی', transliteration: 'Abtahi', en: { meaning: 'Abtahi' }, ur: { meaning: 'ابطحی' } },
  { name: 'مُجْتَبٰی', transliteration: 'Mujtaba', en: { meaning: 'The Chosen' }, ur: { meaning: 'منتخب' } },
  { name: 'أَمِين', transliteration: 'Amin', en: { meaning: 'The Safe' }, ur: { meaning: 'امین' } },
  { name: 'يَسٓ', transliteration: 'Yasin', en: { meaning: 'Yasin' }, ur: { meaning: 'یسین' } },
  { name: 'طٰهٰ', transliteration: 'Taha', en: { meaning: 'Taha' }, ur: { meaning: 'طہٰ' } },
  { name: 'مُرْتَضٰی', transliteration: 'Murtada', en: { meaning: 'The Chosen One' }, ur: { meaning: 'مرتضیٰ' } },
  { name: 'مُصْطَفٰی', transliteration: 'Mustafa', en: { meaning: 'The Selected One' }, ur: { meaning: 'مصطفیٰ' } },
  { name: 'مُقْتَدَی', transliteration: 'Muqtada', en: { meaning: 'The Followed' }, ur: { meaning: 'مقتدیٰ' } },
  { name: 'مُبَارَك', transliteration: 'Mubarak', en: { meaning: 'The Blessed' }, ur: { meaning: 'مبارک' } },
];
